LDLIBS=-lstdc++ -lsfml-graphics -lsfml-window -lsfml-system -lm -lpthread
CXXFLAGS=-O3

gnomderer: gnomderer.o real.o geometry.o raytracer.o sphere.o triangle.o quadrangle.o color.o kdtree.o entity.o
